name: Scheduled Health Check

# Controls when the action will run.
on:
  schedule:
    - cron: "30 * * * *"

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh

      - name: Send Telegram MSG if check fail
        uses: appleboy/telegram-action@master
        with:
           to: ${{ secrets.TELEGRAM_NOTIFY_GROUP }}
           token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
           if: failure()
           message: |
            [SCHEDULED HEALCHECK] 
            One or more HPCC services are unaccessible. 
            Please check the status at https://hpccbk.github.io/status/
